name: Validar código y desplegar contenido estático a Github Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HTML5 Validator
        run: |
          for file in $(find . -name "*.html"); do
            npx html-validator-cli --file=$file
          done 
      

